# Generated by Django 4.2.20 on 2025-03-30 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artists', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_name', models.CharField(max_length=255)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('audio_url', models.URLField(blank=True, null=True)),
                ('plays', models.IntegerField(default=0)),
                ('lyrics_text', models.TextField(blank=True, null=True)),
                ('source', models.TextField(blank=True, null=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artists.artist')),
                ('genres', models.ManyToManyField(to='songs.genres')),
            ],
        ),
    ]
