# Generated by Django 4.2.20 on 2025-03-30 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0002_genres_description_song_is_deleted_song_release_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='audio_url',
        ),
        migrations.AddField(
            model_name='song',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='audio/'),
        ),
    ]
