# Generated by Django 4.2.20 on 2025-04-28 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0003_remove_song_audio_url_song_audio'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
