# Generated by Django 4.2.20 on 2025-05-08 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0005_alter_song_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='thumbnail',
            field=models.FileField(blank=True, null=True, upload_to='thumbnails/'),
        ),
    ]
