# Generated by Django 4.2.20 on 2025-04-10 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0003_remove_song_audio_url_song_audio'),
        ('playlists', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='playlist_cover_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='song',
            field=models.ManyToManyField(blank=True, to='songs.song'),
        ),
    ]
