# Generated by Django 4.2.20 on 2025-04-10 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0002_alter_playlist_playlist_cover_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
