# Generated by Django 4.2.20 on 2025-03-30 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artist',
            old_name='is_detected',
            new_name='is_deleted',
        ),
    ]
